### ISSUE TITLE
IllIllI - One can never lend via the Sense flavor of `lend()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#102]
IllIllI

medium

# One can never lend via the Sense flavor of `lend()`

## Summary

One can never lend via the Sense flavor of `lend()`

## Vulnerability Detail

Most of the protocols that require the user of the `Converter` contract have code that approves the `Converter` for that protocol, but there is no such approval for Sense.

## Impact

_Smart contract unable to operate due to lack of token funds_

Users will be unable to use the Sense lending functionality.

## Code Snippet

The Sense flavor of `lend()` requires the use of the `ISensePeriphery`:
```solidity
// File: src/Lender.sol : Lender.lend()   #1

715            // Determine lent amount after fees
716            uint256 lent = a - fee;
717    
718            // Stores the amount of principal tokens received in swap for underlying
719            uint256 received;
720            {
721                // Get the starting balance of the principal token
722                uint256 starting = token.balanceOf(address(this));
723    
724                // Swap those tokens for the principal tokens
725 @>             ISensePeriphery(x).swapUnderlyingForPTs(adapter, s, lent, r);
726    
727                // Calculate number of principal tokens received in the swap
728                received = token.balanceOf(address(this)) - starting;
729    
730                // Verify that we received the principal tokens
731                if (received < r) {
732                    revert Exception(11, 0, 0, address(0), address(0));
733                }
734            }
735:   
```
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L715-L735

But there is no code that approves the `ISensePeriphery` to be able to withdraw from the `Lender`, except for the rescue functions. If an `ISensePeriphery` is required for a market to function, it should be approved in one of the normal approval functions, rather than one of the just-in-case-training-wheels functions.

There is a fork test that tests the lend functionalty, but is uses `vm.startPrank()` to [hack the approval](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/test/fork/Lender.t.sol#L358-L360), which wouldn't be available in real life.

## Tool used

Manual Review

## Recommendation
Add the ISensePeriphery to the list of contracts that are approved when a market is created or a principal is set

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/266
