### ISSUE TITLE
IllIllI - Illuminate's PTs burn more tokens than are necessary

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#115]
IllIllI

high

# Illuminate's PTs burn more tokens than are necessary

## Summary

Illuminate's PTs burn more tokens than are necessary to get a specific number of underlying, leading to users getting fewer underlying than they deserve

## Vulnerability Detail

`ERC5095.withdraw()/redeem()`'s code relies on `Redeemer.authRedeem()` to do the redemption, but this function always burns the specific amount of PT passed to it, regardless of whether the of whether the PT is worth more than one underlying, which may be the case if there is positive slippage/rewards when the external PT is redeemed, or if the underlying is a rebasing token.

While there are no currently-rebasing underlying tokens listed in the `Contracts.sol` test file, USDC is listed and is an upgradeable contract, which means it may have such functionality in the future for markets that already have users.

## Impact

_Theft of unclaimed yield_

Users will get less underlying than they are owed, even though the code is attempting to track funds on a per-share basis, rather than a one-for-one basis.

## Code Snippet

The NatSpec says `Burns 'shares' from 'owner' and sends exactly 'assets' of underlying tokens to 'receiver'`, and `shares` is the output parameter (since no other argument has this name), so it's clear that the intention is to provide an exact number of assets, not more. In spite of this, the function calls `Redeemer.authRedeem()`...:
```solidity
// File: src/tokens/ERC5095.sol : ERC5095.withdraw()   #1

252                if (o == msg.sender) {
253                    return
254 @>                     IRedeemer(redeemer).authRedeem(
255                            underlying,
256                            maturity,
257                            msg.sender,
258                            r,
259                            a
260                        );
261                } else {
262                    uint256 allowance = _allowance[o][msg.sender];
263                    if (allowance < a) {
264                        revert Exception(20, allowance, a, address(0), address(0));
265                    }
266                    _allowance[o][msg.sender] = allowance - a;
267                    return
268 @>                     IRedeemer(redeemer).authRedeem(
269                            underlying,
270                            maturity,
271                            o,
272                            r,
273                            a
274                        );
275                }
276            }
277:       }
```
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L252-L277

...which always burns the full amount of PTs, even if that results in too many underlying being transferred:
```solidity
// File: src/Redeemer.sol : Redeemer.authRedeem()   #2

463            // Calculate the amount redeemed
464 @>         uint256 redeemed = (a * holdings[u][m]) / pt.totalSupply();
465    
466            // Update holdings of underlying
467            holdings[u][m] = holdings[u][m] - redeemed;
468    
469            // Burn the user's principal tokens
470 @>         pt.authBurn(f, a);
471    
472            // Transfer the original underlying token back to the user
473            Safe.transfer(IERC20(u), t, redeemed);
474:   
```
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Redeemer.sol#L463-L474

## Tool used

Manual Review

## Recommendation
Change the behavior of `authRedeem()` to calculate how many PTs are required to send the right number of underlying, and only burn that many

**Comment by IAm0x52** [comment]
Escalate for 10 USDC

`While there are no currently-rebasing underlying tokens listed in the Contracts.sol test file, USDC is listed and is an upgradeable contract, which means it may have such functionality in the future for markets that already have users.`

Watson clearly acknowledges external factors required for loss of funds. Seems like very low risk to me. If USDC were to upgrade to a rebasing token nearly every existing protocol would start having issues.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> `While there are no currently-rebasing underlying tokens listed in the Contracts.sol test file, USDC is listed and is an upgradeable contract, which means it may have such functionality in the future for markets that already have users.`
> 
> Watson clearly acknowledges external factors required for loss of funds. Seems like very low risk to me. If USDC were to upgrade to a rebasing token nearly every existing protocol would start having issues.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KenzoAgada** [comment]
Escalate for 50 USDC
See 0052's comment above. External factors needed, no real danger at the moment, seems user funds are not really at risk.
Just submitting as a higher stake.

**Comment by sherlock-admin** [comment]
> Escalate for 50 USDC
> See 0052's comment above. External factors needed, no real danger at the moment, seems user funds are not really at risk.
> Just submitting as a higher stake.

You've created a valid escalation for 50 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted. Assigning low risk.

**Comment by sherlock-admin** [comment]
> Escalation accepted. Assigning low risk.

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
