### ISSUE TITLE
hansfriese - Some `Lender.lend()` functions don't validate `p` parameter properly.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#127]
hansfriese

medium

# Some `Lender.lend()` functions don't validate `p` parameter properly.

## Summary
Some `Lender.lend()` functions don't validate `p` parameter properly.

## Vulnerability Detail
In the `Lender.sol`, there are many `lend()` functions to lend out the principal tokens from several AMM protocols.

When we check the first 2 `lend()` functions for [Illuminate and Yield](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L307-L312) and [Swivel](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L372-L381), there are validations of the `p` so that it will revert when the users call the functions with the wrong `p` parameter.

```solidity
    function lend(
        uint8 p,
        address u,
        uint256 m,
        uint256[] memory a,
        address y,
        Swivel.Order[] calldata o,
        Swivel.Components[] calldata s,
        bool e,
        uint256 premiumSlippage
    ) external unpaused(u, m, p) returns (uint256) {
        {
            // Check that the principal is Swivel
            if (p != uint8(MarketPlace.Principals.Swivel)) {
                revert Exception(
                    6,
                    p,
                    uint8(MarketPlace.Principals.Swivel),
                    address(0),
                    address(0)
                );
            }
```

But other `lend()` functions like [this one](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L461) don't validate the `p` at all and it might work unexpectedly when the users use the wrong `p`.

## Impact
Several `lend()` functions might work unexpectedly when the users call the `lend()` functions with the incorrect `p` parameter.

## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L461
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L521
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L572
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L632
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L693
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L750

## Tool used
Manual Review

## Recommendation
Recommend adding the validation of `p` for all `lend()` functions.

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/261
