### ISSUE TITLE
hansfriese - `ERC5095.maxRedeem()` returns the incorrect output.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#128]
hansfriese

medium

# `ERC5095.maxRedeem()` returns the incorrect output.

## Summary
`ERC5095.maxRedeem()` returns the incorrect output.

## Vulnerability Detail
`ERC5095.maxRedeem()` calls `previewRedeem()` before the maturity like below.

```solidity
    function maxRedeem(address o) external view override returns (uint256) {
        if (block.timestamp < maturity) {
            return previewRedeem(_balanceOf[o]); //@audit
        }
        return _balanceOf[o];
    }
```

Logically `maxRedeem()` should return the maximum amount of principal tokens that the owner can redeem but `previewRedeem()` returns the amount of underlying returned by the principal token.

The maximum amount of principal token won't be changed before/after maturity and `maxRedeem()` should return `_balanceOf[o]` for all cases.

## Impact
`ERC5095.maxRedeem()` returns the wrong result of an underlying token.

## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L88-L93

## Tool used
Manual Review

## Recommendation
Recommend modifying like below.

```solidity
    function maxRedeem(address o) external view override returns (uint256) {
        return _balanceOf[o];
    }
```

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/254
