### ISSUE TITLE
hansfriese - `ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` check the maturity condition wrongly.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#131]
hansfriese

medium

# `ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` check the maturity condition wrongly.

## Summary
`ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` check the maturity condition wrongly.

## Vulnerability Detail
`ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` calculate the result differently when the token is matured or not.

```solidity
    function previewRedeem(uint256 s) public view override returns (uint256) {
        if (block.timestamp > maturity) { //@audit >=
            return s;
        }
        return IYield(pool).sellFYTokenPreview(Cast.u128(s));
    }

    /// @notice Post or at maturity simulates the effects of withdrawal at the current block. Pre maturity simulates the amount of `shares` in PT necessary to receive `assets` in underlying from a sale of PT on a YieldSpace AMM.
    /// @param a the amount of underlying tokens withdrawn in the simulation
    /// @return uint256 The amount of principal tokens required for the withdrawal of `assets`
    function previewWithdraw(uint256 a) public view override returns (uint256) {
        if (block.timestamp > maturity) { //@audit >=
            return a;
        }
        return IYield(pool).buyBasePreview(Cast.u128(a));
    }
```

As we can know from other functions [like this one](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L79-L81), we consider the token is matured if `block.timestamp >= maturity`.

But `ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` check the maturity condition as `block.timestamp > maturity` so that they will use the buy/sell functions of the pool instead of using 1:1 formula when `block.timestamp == maturity`.

After all, they might return the wrong result when `block.timestamp == maturity`.

## Impact
`ERC5095.previewRedeem()` and `ERC5095.previewWithdraw()` return the wrong result when `block.timestamp == maturity`.

## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L128-L143

## Tool used
Manual Review

## Recommendation
We should modify like the below.

```solidity
    function previewRedeem(uint256 s) public view override returns (uint256) {
        if (block.timestamp >= maturity) {
            return s;
        }
        return IYield(pool).sellFYTokenPreview(Cast.u128(s));
    }

    /// @notice Post or at maturity simulates the effects of withdrawal at the current block. Pre maturity simulates the amount of `shares` in PT necessary to receive `assets` in underlying from a sale of PT on a YieldSpace AMM.
    /// @param a the amount of underlying tokens withdrawn in the simulation
    /// @return uint256 The amount of principal tokens required for the withdrawal of `assets`
    function previewWithdraw(uint256 a) public view override returns (uint256) {
        if (block.timestamp >= maturity) {
            return a;
        }
        return IYield(pool).buyBasePreview(Cast.u128(a));
    }
```

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/251
