### ISSUE TITLE
ctf_sec - Swivel redeem function parameter signature mismatch in Redeemer.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#145]
ctf_sec

high

# Swivel redeem function parameter signature mismatch in Redeemer.sol

## Summary

Swivel redeem function signature mismatch in Redeemer.sol

## Vulnerability Detail

The redeem function for Swivel is implemented below:

```solidity
if (p == uint8(MarketPlace.Principals.Swivel)) {
    // Redeems principal tokens from Swivel
    if (!ISwivel(swivelAddr).redeemZcToken(u, maturity, amount)) {
        revert Exception(15, 0, 0, address(0), address(0));
    }
```

We can look into the redeemZcToken interface:

```solidity
function redeemZcToken(
    address u,
    uint256 m,
    uint256 a
) external returns (bool);
```

And we compare with the redeemZcToken implementation for Swivel's github:

https://github.com/Swivel-Finance/swivel/blob/3cc31302f84c2b1777a53c11b22c58ec6ef17888/contracts/v3/src/Swivel.sol#L1007

```solidity
    /// @notice Allows zcToken holders to redeem their tokens for underlying tokens after maturity has been reached (via MarketPlace).
    /// @param p Protocol Enum value associated with this market pair
    /// @param u Underlying token address associated with the market
    /// @param m Maturity timestamp of the market
    /// @param a Amount of zcTokens being redeemed
    function redeemZcToken(
        uint8 p,
        address u,
        uint256 m,
        uint256 a
    ) external returns (bool) {
```

We miss-matched the parameter and function signature!

## Impact

Redeem for swivel will not work.

## Code Snippet

https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Redeemer.sol#L277-L282

https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/interfaces/ISwivel.sol#L6-L19

## Tool used

Manual Review

## Recommendation

We recommend making the interface align with the implementation:

We change from 

```solidity
function redeemZcToken(
    address u,
    uint256 m,
    uint256 a
) external returns (bool);
```

to

```solidity
function redeemZcToken(
    uint8 p,
    address u,
    uint256 m,
    uint256 a
) external returns (bool);
```

and we change from

```solidity
if (!ISwivel(swivelAddr).redeemZcToken(u, maturity, amount)) {
    revert Exception(15, 0, 0, address(0), address(0));
}
```

to

```solidity
if (!ISwivel(swivelAddr).redeemZcToken(p, u, maturity, amount)) {
    revert Exception(15, 0, 0, address(0), address(0));
}
```

**Comment by IAm0x52** [comment]
Escalate for 10 USDC

Agree with @IllIllI000, don't think this can be a valid issue considering contest code was explicitly designed to work with V2 not V3.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Agree with @IllIllI000, don't think this can be a valid issue considering contest code was explicitly designed to work with V2 not V3.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KenzoAgada** [comment]
Escalate for 50 USDC
Same reasoning as 52 above, just giving a higher stake amount.
> Agree with @IllIllI000, don't think this can be a valid issue considering contest code was explicitly designed to work with V2 not V3.

**Comment by sherlock-admin** [comment]
> Escalate for 50 USDC
> Same reasoning as 52 above, just giving a higher stake amount.
> > Agree with @IllIllI000, don't think this can be a valid issue considering contest code was explicitly designed to work with V2 not V3.

You've created a valid escalation for 50 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/234
