### ISSUE TITLE
pashov - Some tokens (USDT) expect to always have zero allowances before approving a non-uint256.max amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#167]
pashov

medium

# Some tokens (USDT) expect to always have zero allowances before approving a non-uint256.max amount

## Summary
The code approves non-zero and non-uint256.max amount for a token without first approving `0`. This will always revert if the token is `USDT`

## Vulnerability Detail
Some tokens (e.g. USDT, KNC) do not allow approving an amount M > 0 when an existing amount N > 0 is already approved. This is to protect from an ERC20 attack vector described [here](https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit#heading=h.b32yfk54vyg9)
In `convert` method in `Converter.sol` for example we have `Safe.approve(IERC20(u), pool, a);` which will always revert if the `pool` address still has allowance > 0 and `u` token is `USDT`.

## Impact
The impact is DoS for using a common token - `USDT`. Still, it is a special case, so Medium severity should be appropriate

## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Converter.sol#L32

## Tool used

Manual Review

## Recommendation

Before doing `approve`, always approve `0` amount first, for example for the code `Safe.approve(IERC20(token), pool, 0)`

Duplicate of https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/99

**Comment by dmitriia** [comment]
Escalate for 20 USDC

This looks invalid as to suggest `approve(0)` it is needed to show a way for an allowance to not be used fully. I.e. if an allowance is set to `a > 0`, and this `a` is fully used *all the time*, then there is no issue.

Here it is not shown that aTokens redemption can be partial and `IAaveLendingPool(pool).withdraw(u, a, msg.sender)` can for any reason utilize less than `a`, leaving the positive allowance behind. If it is not the case there is no reason for USDT to revert and this is why the corresponding test works.

**Comment by sherlock-admin** [comment]
> Escalate for 20 USDC
> 
> This looks invalid as to suggest `approve(0)` it is needed to show a way for an allowance to not be used fully. I.e. if an allowance is set to `a > 0`, and this `a` is fully used *all the time*, then there is no issue.
> 
> Here it is not shown that aTokens redemption can be partial and `IAaveLendingPool(pool).withdraw(u, a, msg.sender)` can for any reason utilize less than `a`, leaving the positive allowance behind. If it is not the case there is no reason for USDT to revert and this is why the corresponding test works.
> 
> 

You've created a valid escalation for 20 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/265
