### ISSUE TITLE
pashov - `Marketplace.sol` is checking the incorrect variable for slippage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#175]
pashov

medium

# `Marketplace.sol` is checking the incorrect variable for slippage

## Summary
The functionalities for buying and selling underlying and principal tokens check the incorrect value for slippage

## Vulnerability Detail
The four methods in `Marketplace.sol` for buying/selling underlying/principal tokens all do the same thing for checking slippage tolerance (example from `sellPrincipalToken`): 
```jsx
uint256 expected = pool.sellFYTokenPreview(a);

        if (expected < s) {
            revert Exception(16, expected, s, address(0), address(0));
        }

        // Transfer the principal tokens to the pool
        Safe.transferFrom(
            IERC20(address(pool.fyToken())),
            msg.sender,
            address(pool),
            a
        );

        // Execute the swap
        uint128 received = pool.sellFYToken(msg.sender, uint128(expected));
```
Here the slippage is checked against `expected` instead of against `received`. This way if the preview function of the pool is unreliable (usually preview functions are unreliable and only advised to be used off-chain) the user can actually receive less tokens than what he set as `minTokensIn`.
## Impact
The impact is potentially bigger loss for users than what they set they are fine with, hence medium severity

## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L297
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L336
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L374
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L408
## Tool used

Manual Review

## Recommendation
Change the checks in the four mentioned methods to compare `s` (slippage tolerance argument) with `received` variable, not `expected`

Duplicate of https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/181

**Comment by pashov** [comment]
Escalate for 5 USDC

This is not a duplicate of #181 even though they are related. While 181 suggests adding a slippage parameter in `ERC5095` , this issue calls for changing the slippage check in `Marketplace`

**Comment by sherlock-admin** [comment]
> Escalate for 5 USDC
> 
> This is not a duplicate of #181 even though they are related. While 181 suggests adding a slippage parameter in `ERC5095` , this issue calls for changing the slippage check in `Marketplace`

You've created a valid escalation for 5 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.
