### ISSUE TITLE
__141345__ - Slippage control should use `shares` rather than `assets`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#202]
__141345__

medium

# Slippage control should use `shares` rather than `assets`

## Summary

In `mint()`, the slippage control parameter is using the underlying `assets`, but it should use the PT token `shares`.

## Vulnerability Detail

When `sellUnderlying()`, the token received is the PT token, the units to calculate the slippage should be the shares of PT token, rather than the underlying.

## Impact

- wrong value of PT token could be minted in big slippage, and lead to user fund loss.
- the `mint()` could revert due to wrong slippage control.

## Code Snippet

https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L194-L199

## Tool used

Manual Review

## Recommendation

Use `shares` rather than `assets`.

Duplicate of #225

**Comment by 141345** [comment]
Escalate for 21 USDC

This is a duplicate of https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/31

**Comment by sherlock-admin** [comment]
> Escalate for 21 USDC
> 
> This is a duplicate of https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/31

You've created a valid escalation for 21 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.
