### ISSUE TITLE
__141345__ - `autoRedeem()` should check PT allowance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#205]
__141345__

high

# `autoRedeem()` should check PT allowance

## Summary

In `autoRedeem()`, `uToken` allowance is checked instead of PT allowance. But according to the purpose of this function, it should be the PT allowance.

## Vulnerability Detail

`uToken` allowance would probably be 0, hence the `if (allowance < amount)` will fail. The `autoRedeem()` function will revert. 

## Impact

Users fund could be locked.

## Code Snippet

https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Redeemer.sol#L511-L528

## Tool used

Manual Review

## Recommendation

Change to 
```solidity
        uint256 allowance = pt.allowance(f[i], address(this));
```

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/241
