### ISSUE TITLE
kenzo - Protocol will lose fees when lending on Swivel and swapping in YieldPool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#24]
kenzo

medium

# Protocol will lose fees when lending on Swivel and swapping in YieldPool

## Summary
When a user uses `Lender.lend` to lend on Swivel, and passes `e=true` so remainder of funds will be swapped in YieldPool,
The contract will send to the YieldPool the order's protocol fee as well.

## Vulnerability Detail
Detailed above and in the code snippet below.

## Impact
Protocol funds will be lost, as user will not pay fee for this order.
Fees accounting will be wrong, as `fees` contains fees which are not present in the contract. `withdrawFee` will fail (as it tries to withdraw more than balance) and admin will have to withdraw fees using the emergency mechanism.

## Code Snippet
When landing on Swivel, `Lender` will sum up the fees of the order, substract it from the order amount, and then [add](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L400) it to `fees`:
```solidity
                // Add the accumulated fees to the total
                a[lastIndex] = a[lastIndex] - fee; // Revert here if fee not paid
                // Extract fee
                fees[u] += fee;
```
After initiating the Swivel order, the function checks what's the underlying remainder, and [sends](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L417) it to Yield to swap to iPTs:
```solidity
                if (e) {
                    // Calculate the premium
                    uint256 premium = IERC20(u).balanceOf(address(this)) - starting;
                    // Swap the premium for Illuminate principal tokens
                    swivelLendPremium(u, m, y, premium, premiumSlippage);
                }
```
Note that since the fees have not been sent to Swivel, they are included in the `premium` delta.
They are then sent to be swapped on Yield using `swivelLendPremium`.
Therefore, the fees will be lost, the accounting will be off, and `withdrawFee` [will revert](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L862) when it tries to send more than the contract's balance.

## Tool used
Manual Review

## Recommendation
Deduct `fee` from `premium`.

Duplicate of #45

**Comment by KenzoAgada** [comment]
Escalate for 100 USDC
This is a different issue than #45.
There are 2 amounts in this Swivel lending function: `a` (order amount to Swivel) and `premium` (underlying remainder to be swapped on YieldPool).
In #45, the problem is that the user swaps `premium` without paying fees for swapping `premium`.
In this one, the problem is that the fees *that were already deducted from `a`* will be *swapped as part of `premium`*, therefore **the protocol would totally lose the fees** and `withdrawFee` will revert as accounting will be off.

Please note that as a watson escalated in another issue, protocol fees are generally considered to be high severity, so maybe also this should be upgraded to high.

Note, @sourabhmarathe , you'll want to fix both issues.
to fix this issue you'll need to deduct `fee` from `premium`:
```solidity
                    uint256 premium = IERC20(u).balanceOf(address(this)) - starting - fee;
```
and to fix #45 you'll need to deduct the new fee from `premium`, so can add the following after previous line:
```solidity
                    fee = premium / feenominator;
                    premium = premium - fee;
                    fees[u] += fee;
```

**Comment by sherlock-admin** [comment]
> Escalate for 100 USDC
> This is a different issue than #45.
> There are 2 amounts in this Swivel lending function: `a` (order amount to Swivel) and `premium` (underlying remainder to be swapped on YieldPool).
> In #45, the problem is that the user swaps `premium` without paying fees for swapping `premium`.
> In this one, the problem is that the fees *that were already deducted from `a`* will be *swapped as part of `premium`*, therefore **the protocol would totally lose the fees** and `withdrawFee` will revert as accounting will be off.
> 
> Please note that as a watson escalated in another issue, protocol fees are generally considered to be high severity, so maybe also this should be upgraded to high.
> 
> Note, @sourabhmarathe , you'll want to fix both issues.
> to fix this issue you'll need to deduct `fee` from `premium`:
> ```solidity
>                     uint256 premium = IERC20(u).balanceOf(address(this)) - starting - fee;
> ```
> and to fix #45 you'll need to deduct the new fee from `premium`, so can add the following after previous line:
> ```solidity
>                     fee = premium / feenominator;
>                     premium = premium - fee;
>                     fees[u] += fee;
> ```

You've created a valid escalation for 100 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation rejected.

Both issues address an accounting problem related to the `fee` and the `premium`, this can easily be described as a single issue, especially because both issues recommend a fix on the same line of code.

**Comment by sherlock-admin** [comment]
> Escalation rejected.
> 
> Both issues address an accounting problem related to the `fee` and the `premium`, this can easily be described as a single issue, especially because both issues recommend a fix on the same line of code. 
> 
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
