### ISSUE TITLE
caventa - Unsafe casting from int128 can cause the wrong accounting amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#42]
caventa

medium

# Unsafe casting from int128 can cause the wrong accounting amount

## Summary
Unsafe casting from int128 can cause the wrong accounting amount.

## Vulnerability Detail
The unsafe casting to int128 variable (See Marketplace.sol#L310) can cause its value to be different from the original value. 

## Impact
In this case, if the value is greater than type(int128).max which is 2**127 - 1, then the accounting will be wrong and the amount will be less than the amount of the token.
 
## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L310
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L940
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/lib/Cast.sol#L10

## Tool used
Manual Review

## Recommendation
Using Cast.u128 to do casting is a better option because it will revert the transaction if the amount is larger than 2**127 - 1. Cast.u128 is used several times in Lender.sol (See Lender.sol#L940) and ERC5095.sol, which I think the developer should use the same approach too.

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/257
