### ISSUE TITLE
neumo - Setting a pool in Marketplace should enforce that underlying and maturity match the pool's base token and maturity respectively

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#52]
neumo

high

# Setting a pool in Marketplace should enforce that underlying and maturity match the pool's base token and maturity respectively

## Summary
If a pool is set for a `[underlying, maturity]` pair, there is no check to validate that the **underlying** matches the pool's **base** token and that the **maturity** matches that of the pool. Together with the fact that once a pool is set for a `[underlying, maturity]` pair it cannot be changed, could lead to a unusable market.

## Vulnerability Detail
In **Marketplace** contract, when the admin adds a pool via **setPool** there is no check that the underlying token matches the pool's base token and its maturity.
This is the code of the setPool function:
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L259-L277
It first gets the pool for the `[underlying, maturity]` pair from the pool's mapping and then checks if it is already set (!=0). If so, it reverts, making impossible to update the pool. If it's not set, it does `pools[u][m] = a;` to set the pool to the address provided. It checks nowhere that the underlying (u) and the maturity (m) match the pool's base token and maturity respectively. If the call to **setPool** is made with the wrong **Pool** address, being it an irreversible action because the pool address cannot be changed, could lead to disastrous consequences and making the protocol fail to deliver the expected behaviour.
## Impact
When underlying tokens or maturities don't match between markets and their pools, the flows of depositing, lending, etc. won't work properly.
For instance, in **ERC5095.sol**'s **mint** function there's a transfer of underlying from the user to Illuminate's principal token. And then there's a call to the **marketplace**'s **sellUnderlying** function.
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/tokens/ERC5095.sol#L187-L199
But this function tries to transfer to the pool its underlying tokens which are not there because the user transferred in a different underlying token (not pool.base()).
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Marketplace.sol#L378-L379
Causing the call to mint to revert.

## Code Snippet
To prove this bad behaviour, I created a test in [ERC5095.t.sol](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/test/fork/ERC5095.t.sol):
```solidity
function testDifferentUnderlyingTokensMint() public {
	uint256 amount = 100000;
	deal(Contracts.USDC, address(this), amount);
	deal(address(token), address(token), amount * 2);
	vm.expectRevert(bytes("YieldMath: Rounding induced error"));
	token.mint(address(this), amount);
}
```
But also changing this line:
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/test/fork/ERC5095.t.sol#L36
With this:
`Contracts.YIELD_POOL_DAI`

To use the DAI pool instead of USDC.
## Tool used

Forge tests and manual Review

## Recommendation
Enforce at market creation that the underlying and maturity match those of the pool:
```solidity
function setPool(
        address u,
        uint256 m,
        address a
    ) external authorized(admin) returns (bool) {
	// Verify that the pool has not already been set
	address pool = pools[u][m];

	// Revert if the pool already exists
	if (pool != address(0)) {
		revert Exception(10, 0, 0, pool, address(0));
	}
	
	// Revert if underlying tokens don't match
	if (u != address(IYield(a).base())) {
		revert Exception(3, 0, 0, pool, address(0));
	}
	
	// Revert if maturities don't match
	if (m != uint256(IYield(a).maturity())) {
		revert Exception(2, 0, 0, pool, address(0));
	}

	// Set the pool
	pools[u][m] = a;

	emit SetPool(u, m, a);
	return true;
}
```
**Note**: The contract should import the **IYield** interface.

duplicate of #103

**Comment by neumoxx** [comment]
Escalate for 20 USDC
The comment in #103 (which is issue is marked as duplicate of)
https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/103#issuecomment-1314672775
States that this will probably be fixed. I don't get why not rewarding a clear issue, maybe #103 does not fit the sherlock scoring guidelines but I think my issue does.

**Comment by sherlock-admin** [comment]
> Escalate for 20 USDC
> The comment in #103 (which is issue is marked as duplicate of)
> https://github.com/sherlock-audit/2022-10-illuminate-judging/issues/103#issuecomment-1314672775
> States that this will probably be fixed. I don't get why not rewarding a clear issue, maybe #103 does not fit the sherlock scoring guidelines but I think my issue does.

You've created a valid escalation for 20 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.
