### ISSUE TITLE
cccz - Incorrect parameters when calling the initiate function, allowing the user to spend the fees in the contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#56]
cccz

high

# Incorrect parameters when calling the initiate function, allowing the user to spend the fees in the contract

## Summary
Incorrect parameters when calling the initiate function, allowing the user to spend the fees in the contract
## Vulnerability Detail
In lend() for Swivel, the parameter when calling the initiate function is `a` , but in fact, in the initiateZcTokenFillingVaultInitiate function of the Swivel contract, `a + fee` tokens will be sent from the Lender contract to the Swivel contract, causes the fee to be actually paid by the Lender contract instead of the user.
```solidity
    function initiateZcTokenFillingVaultInitiate(
        Hash.Order calldata o,
        uint256 a,
        Sig.Components calldata c
    ) internal {
        bytes32 hash = validOrderHash(o, c);
        uint256 amount = a + filled[hash];

        if (amount > o.principal) {
            revert Exception(5, amount, o.principal, address(0), address(0));
        }

        filled[hash] = amount;

        IERC20 uToken = IERC20(o.underlying);

        uint256 premiumFilled = (a * o.premium) / o.principal;
        Safe.transferFrom(uToken, o.maker, msg.sender, premiumFilled);

        // transfer principal + fee in underlying to swivel (from sender)
        uint256 fee = premiumFilled / feenominators[0];
        Safe.transferFrom(uToken, msg.sender, address(this), (a + fee));
```
After that, the withdrawFee function fails because the balance in the contract is less than fees
```solidity
    function withdrawFee(address e) external authorized(admin) returns (bool) {
        // Get the token to be withdrawn
        IERC20 token = IERC20(e);

        // Get the balance to be transferred
        uint256 balance = fees[e];

        // Reset accumulated fees of the token to 0
        fees[e] = 0;

        // Transfer the accumulated fees to the admin
        Safe.transfer(token, admin, balance);

        return true;
    }
```
## Impact
Users can use the Lender contract balance to pay Swivel's fee, and the withdrawFee function will fail
## Code Snippet
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L415-L416
https://github.com/Swivel-Finance/swivel/blob/main/contracts/v3/src/Swivel.sol#L229-L250
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L857-L871
## Tool used

Manual Review

## Recommendation
Consider subtracting Swivel's fee from `a` when calling the initiate function

**Comment by KenzoAgada** [comment]
Escalate for 50 USDC
Seems invalid. Watson says that `a + fee` will be sent from `Lender`, and the recommendation for remediation is "Consider subtracting Swivel's `fee` from `a` when calling the initiate function", but that is already done in [this](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L401) line:
```solidity
                a[lastIndex] = a[lastIndex] - fee; // Revert here if fee not paid
```
Plus it doesn't seem like a duplicate of #45.

**Comment by sherlock-admin** [comment]
> Escalate for 50 USDC
> Seems invalid. Watson says that `a + fee` will be sent from `Lender`, and the recommendation for remediation is "Consider subtracting Swivel's `fee` from `a` when calling the initiate function", but that is already done in [this](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L401) line:
> ```solidity
>                 a[lastIndex] = a[lastIndex] - fee; // Revert here if fee not paid
> ```
> Plus it doesn't seem like a duplicate of #45.

You've created a valid escalation for 50 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by thereksfour** [comment]
My understanding is that the fee here is the fee of illuminate: https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L401
The fee here is the fee of Swivel: https://github.com/Swivel-Finance/swivel/blob/main/contracts/v3/src/Swivel.sol#L250
The protocol shall charge both fees from the user

**Comment by Evert0x** [comment]
Escalation accepted

**Comment by sherlock-admin** [comment]
> Escalation accepted

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
