### ISSUE TITLE
0x52 - Lender allows users to mint PT backed by PT which artificially inflates the supply of PT and damages the exchange rate for all users

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#79]
0x52

high

# Lender allows users to mint PT backed by PT which artificially inflates the supply of PT and damages the exchange rate for all users

## Summary

Lender#mint allows a user to PT to mint PT which inflates the total supply of PT without increasing the underlying. Since the exchange ratio is determined by the total supply of PT it damages the final exchange rate for all users. This can be used maliciously to permanently damage the exchange rate then profit from the attack by calling Redeemer#autoRedeem for the Lender contract and collecting the incentive.

## Vulnerability Detail

    function mint(
        uint8 p,
        address u,
        uint256 m,
        uint256 a
    ) external unpaused(u, m, p) returns (bool) {
        // Fetch the desired principal token
        address principal = IMarketPlace(marketPlace).token(u, m, p);

        // Transfer the users principal tokens to the lender contract
        Safe.transferFrom(IERC20(principal), msg.sender, address(this), a);

        // Mint the tokens received from the user
        IERC5095(principalToken(u, m)).authMint(msg.sender, a);

        emit Mint(p, u, m, a);

        return true;
    }

Lender#mint allows a user to mint PT using shares from any underlying protocol. The reference to the token address for the PT is stored in IMarketPlace(marketPlace).token(u, m, 0). Since the PT isn't disallowed, a user can call mint with p = 0 to mint PT using PT. It can also lead to an attack vector.

Example:

Assume there is a market 1 minute from maturity with 1M PT and 100K PT are in the PT-Underlying pool. An attacker starts by swapping 50K underlying into PT using the PT-Underlying pool. They then call mint with their 50k PT. This moves 50k PT to the Lender contract and mints them 50k more PT. They repeat this 19 more times. The market now has 2M PT, 1M of which is in the Lender contract. The attacker swaps their PT back to recover their initial collateral. After the market has matured, the attacker calls Redeemer#autoRedeem for the Lender contract. autoRedeem has an allowance check but lender has already approved uint256.max because of Lender#approve( u, m, r) approves all protocols including PT to allow for redemption. Since there was 1M legitimate PT before the attack, the Redeemer contract should have ~1M underlying. autoRedeem burns all 1M PT and sends the Lender contract 500K underlying. The attacker collects the fee on 500K. The 500K (minus the fee paid to the attacker) would be recoverable from the lender contract but the exchange rate is permanently skewed and will require governance intervention to setup an alternate redemption method. Additionally the fee paid to the attacker is unrecoverable.

## Impact

Attacker steals the fee on a large amount of collateral and illuminate is left with a gigantic mess

## Code Snippet

[Lender.sol#L270-L288](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L270-L288)

[Lender.sol#L298-L347](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L298-L347)

## Tool used

Manual Review

## Recommendation

It should never be possible to mint PT using PT as collateral. Disallow using PT as collateral in Lender#mint and lend

Duplicate of #108

**Comment by KenzoAgada** [comment]
Escalate for 50 USDC
This is not a duplicate of #208/#213.
208 is about lending or minting after maturity.
This issue is specifically about minting-ipts-through-ipts. At the moment there are duped to #238 but as hyh correctly escalated there, they need their own topic.

**Comment by sherlock-admin** [comment]
> Escalate for 50 USDC
> This is not a duplicate of #208/#213.
> 208 is about lending or minting after maturity.
> This issue is specifically about minting-ipts-through-ipts. At the moment there are duped to #238 but as hyh correctly escalated there, they need their own topic.

You've created a valid escalation for 50 USDC!

To remove the escalation from consideration: Delete your comment.
To change the amount you've staked on this escalation: Edit your comment **(do not create a new comment)**.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Evert0x** [comment]
Escalation accepted.

Although it is a duplicate of #213, I give the escalator the benefit on the doubt that he was referring to the (previous) grouping of 208/213.

**Comment by sherlock-admin** [comment]
> Escalation accepted.
> 
> Although it is a duplicate of #213, I give the escalator the benefit on the doubt that he was referring to the (previous) grouping of 208/213. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/244
