### ISSUE TITLE
IllIllI - Tempus lending only works with unlimited slippage

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-10-illuminate-judging#98]
IllIllI

medium

# Tempus lending only works with unlimited slippage

## Summary

Tempus lending only works when unlimited slippage is allowed

## Vulnerability Detail

The `lend()` function for Tempus relies on the function `TempusController.depositAndFix()`, whose slippage argument is a _rate_ rather than a minimum amount. The `lend()` function passes an amount rather than a rate, and reverts if the amount returned is less than the amount deposited, which is impossible, since the exchange rate will never match a usable amount. The only way to use this Tempus version of `lend()`, as is done in the Illuminate fork tests, is to [pass zero](https://github.com/sherlock-audit/2022-10-illuminate/blob/main/test/fork/Lender.t.sol#L30) as the rate, which means unlimited slippage.

## Impact

_Smart contract unable to operate due to lack of token funds_

Users will be unable to use the Tempus lending functionality, except if they expose themselves to unlimited slippage

## Code Snippet

`depositAndFix()` takes in a rate, not an amount:
```solidity
// File: etherscan/TempusController.sol : depositAndFix()   #1

120      /// @dev Atomically deposits YBT/BT to TempusPool and swaps TYS for TPS to get fixed yield
121      ///      See https://docs.balancer.fi/developers/guides/single-swaps#swap-overview
122      /// @param tempusAMM Tempus AMM to use to swap TYS for TPS
123      /// @param tokenAmount Amount of YBT/BT to be deposited in underlying YBT/BT decimal precision
124      /// @param isBackingToken specifies whether the deposited asset is the Backing Token or Yield Bearing Token
125 @>   /// @param minTYSRate Minimum exchange rate of TYS (denominated in TPS) to receive in exchange for TPS
126      /// @param deadline A timestamp by which the transaction must be completed, otherwise it would revert
127      function depositAndFix(
128          ITempusAMM tempusAMM,
129          uint256 tokenAmount,
130          bool isBackingToken,
131          uint256 minTYSRate,
132          uint256 deadline
133      ) external payable nonReentrant {
134          requireRegistered(address(tempusAMM));
135          _depositAndFix(tempusAMM, tokenAmount, isBackingToken, minTYSRate, deadline);
136:     }
```
https://etherscan.io/address/0xdB5fD0678eED82246b599da6BC36B56157E4beD8#code#F1#L120-136

It's definitely a rate (as is the case with the new Tempus code [too](https://github.com/tempus-finance/fixed-income-protocol/blob/ae8426a94c602b1a0df34ded3589c70d16bf5aa9/contracts/TempusController.sol#L72)):
```solidity
// File: etherscan/TempusController.sol : _depositAndFix()   #2
423:        uint256 minReturn = swapAmount.mulfV(minTYSRate, targetPool.backingTokenONE());
```
https://etherscan.io/address/0xdB5fD0678eED82246b599da6BC36B56157E4beD8#code#F1#L423

As with the other `lend()` functions, `r` is an amount, and is compared against the output amount:
```solidity
// File: src/Lender.sol : Lender.lend()   #3

628 @>     /// @param r minimum amount to return when executing the swap (sets a limit to slippage)
...
654            }
655    
656            // Get the starting balance of the principal token
657            uint256 start = IERC20(principal).balanceOf(address(this));
658    
659            // Get the Tempus Router from the principal token
660            address controller = ITempusPool(ITempusToken(principal).pool())
661                .controller();
662    
663            // Swap on the Tempus Router using the provided market and params
664 @>         ITempus(controller).depositAndFix(x, lent, true, r, d);
665    
666            // Calculate the amount of Tempus principal tokens received after the deposit
667            uint256 received = IERC20(principal).balanceOf(address(this)) - start;
668    
669            // Verify that a minimum number of principal tokens were received
670 @>         if (received < r) {
671                revert Exception(11, received, r, address(0), address(0));
672            }
673    
674:           // Mint Illuminate zero coupons
```
https://github.com/sherlock-audit/2022-10-illuminate/blob/main/src/Lender.sol#L628-L674

The comparison above on line 670 will revert unless used with very small amounts, or zero

## Tool used

Manual Review

## Recommendation

Convert `r` to a rate in the function body, and use that rate as the argument to `depositAndFix()`

Duplicate of #233

**Comment by sourabhmarathe** [comment]
https://github.com/Swivel-Finance/illumigrate/pull/247
